name: "evandrosystems/deploy"
description: "GitHub action to deploy files with ssh"
author: "Evandro Alves"

branding:
  icon: "upload"
  color: "blue"

inputs:
  user:
    description: "Server username"
    required: true
  host:
    description: "Server host"
    required: true
  port:
    description: "Server port"
    required: false
    default: "22"
  key:
    description: "SSH private key"
    required: true
  data:
    description: "Source files"
    required: true
  dir:
    description: "Destination folder"
    required: true
  exclude:
    description: "Files to exclude"
    required: false
  before-commands:
    description: "Commands to run before deploying"
    required: false
  after-commands:
    description: "Commands to run after deploying"
    required: false


runs:
  using: "node20"
  main: "dist/index.js"